apiVersion: v1
description: A Helm chart for eventrouter (https://github.com/heptiolabs/eventrouter)
name: chiara-app
appVersion: 0.3.0
home: https://github.com/heptiolabs/eventrouter
sources:
- https://github.com/heptiolabs/eventrouter
keywords:
- eventrouter
maintainers:
- name: gianrubio
  email: gianrubio@gmail.com
version: [[ .Version ]]
\n