apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: chiara-app 
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: chiara-app 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chiara-app
subjects:
- kind: ServiceAccount
  name: chiara-app
  namespace: kube-system